"""empty message

Revision ID: 0a007fde5955
Revises: a5cffa318ac2
Create Date: 2025-07-06 18:44:39.196383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a007fde5955'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.Integer(), nullable=False),
    sa.Column('ap', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('hpreg', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('manareg', sa.Integer(), nullable=False),
    sa.Column('atspeed', sa.Integer(), nullable=False),
    sa.Column('crit', sa.Integer(), nullable=False),
    sa.Column('cd', sa.Integer(), nullable=False),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('mresist', sa.Integer(), nullable=False),
    sa.Column('armorpen', sa.Integer(), nullable=False),
    sa.Column('magicpen', sa.Integer(), nullable=False),
    sa.Column('lethal', sa.Integer(), nullable=False),
    sa.Column('mvspeed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nick', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', 'NA', name='enumgender'), nullable=False),
    sa.Column('rank', sa.Enum('Diamond', 'Master', 'Grandmaster', 'Challenger', 'NA', name='enumrank'), nullable=False),
    sa.Column('mainrole', sa.Enum('Top', 'Jungle', 'Mid', 'ADCarry', 'Support', 'NA', name='enumlane'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nick'),
    sa.UniqueConstraint('username')
    )
    op.create_table('champions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lane', sa.Enum('Top', 'Jungle', 'Mid', 'ADCarry', 'Support', 'NA', name='enumlane'), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('media', sa.String(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('media', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('builditems',
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'item_id')
    )
    op.create_table('favourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'build_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('favourites')
    op.drop_table('builditems')
    op.drop_table('builds')
    op.drop_table('items')
    op.drop_table('champions')
    op.drop_table('users')
    op.drop_table('stats')
    # ### end Alembic commands ###
