"""empty message

Revision ID: 1aaf09435e9b
Revises: 0a007fde5955
Create Date: 2025-07-06 19:18:04.563179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aaf09435e9b'
down_revision = '0a007fde5955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lifesteal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('spellvamp', sa.Integer(), nullable=False))
        batch_op.alter_column('atspeed',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.alter_column('atspeed',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('spellvamp')
        batch_op.drop_column('lifesteal')

    # ### end Alembic commands ###
